# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and run all unit tests"
  lane :build_and_unit_test do |options|
    scan(
    	scheme: "jenkinsTraining",
    	workspace: "jenkinsTraining.xcworkspace",
    	skip_testing: "jenkinsTrainingUITests",
    	output_directory: "#{ENV['OUTPUT_DIRECTORY']}",
    	configuration: options[:configuration]
    	)
  end

  desc "Firebase distribution"
  lane :firebase_distribution do
    firebase_app_distribution(
      ipa_path: "#{ENV['OUTPUT_DIRECTORY']}/#{ENV['IPA_NAME']}",
      service_credentials_file: "/Users/luis.gomez/Downloads/{name}.json",
      app: "#{ENV['FIREBASE_IOS_APP_ID']}",
      groups: "{group name}, {group name 2}"
    )
    upload_symbols_to_crashlytics(dsym_path: "#{ENV['OUTPUT_DIRECTORY']}}")
  end

  desc "Testflight distribution"
  lane :testflight_distribution do
    api_key = app_store_connect_api_key(
      key_id: "#{ENV['APP_STORE_API_KEY']}",
      issuer_id: "#{ENV["APP_STORE_ISSUER_ID"]}",
      key_filepath: "#{ENV["APP_STORE_API_KEY_PATH"]}",
      in_house: true
    )
    upload_to_testflight(
      ipa: "#{ENV['OUTPUT_DIRECTORY']}/#{ENV['IPA_NAME']}",
      app_identifier: "lagv.jenkinsTraining",
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
