# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and run all unit tests"
  lane :build_and_unit_test do |options|
    scan(
    	scheme: "jenkinsTraining",
    	workspace: "jenkinsTraining.xcworkspace",
    	skip_testing: "jenkinsTrainingUITests",
    	output_directory: "#{ENV['OUTPUT_DIRECTORY']}"
    	)
  end
end
