pipeline {
    //agent any
    agent { label 'master' }

    stages {
        stage('Stage name 1') {
            steps {
                echo 'Stage 1 started'
            }
        }
    }

    post {
        success {
            echo 'Yuhuuuu'
        }
        failure {
            echo 'Ouch'
        }
    	always {
            echo 'CI finished'
    	}
    }
}