pipeline {
    //agent any
    agent { label 'master' }

    environment {
        OUTPUT_DIRECTORY = ".output"
    }

    stages {
        stage('Pod install') {
            steps {
                echo 'Installing pods...'
                sh 'pod install'
            }
        }
        stage('Build and test') {
            steps {
                //catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                sh 'fastlane build_and_unit_test configuration:Debug'
                //}
            }
        }
    }

    post {
        success {
            echo 'Yuhuuuu'
        }
        failure {
            echo 'Ouch'
        }
    	always {
            echo 'CI finished'
            echo 'Saving artifacts ...'
            archiveArtifacts artifacts: "${OUTPUT_DIRECTORY}/*.*"
    	}
    }
}